#!/bin/sh -
#
#
PATH=/bin:/sbin:/usr/sbin:/usr/bin:/usr/local/bin/

url='https://services.swpc.noaa.gov/text/3-day-forecast.txt'
tmp_a=`mktemp`

ftp -o - $url | grep -C4 "09-12UT" | grep -C4 "09-12UT" | sed "s/^.*UT//; s/^[ \t]*//g; s/[ \t]*$//; s/  /-/g; s/--/%/g; s/% /|/g; s/%%/|/g; s/|-/|/g" > $tmp_a
day_0=`cat $tmp_a | head -1 | awk -F"|" '{print $1}'`
day_1=`cat $tmp_a | head -1 | awk -F"|" '{print $2}'`
day_2=`cat $tmp_a | head -1 | awk -F"|" '{print $3}'`

if [ "`date -u "+%b %d"`" == "$day_0" ]||[ "`date -u "+%b %d"`" == "$day_1" ]||[ "`date -u "+%b %d"`" == "$day_2" ]; then
    
    if [ "`date -u "+%b %d"`" == "$day_2" ]; then
        echo "Something's wrong with the 3-day-forecast.txt aurora report" | mail -s"aurora next hours error" hugo
    fi
    
    tmp_b=`mktemp`
    now=`date -u +%s`
    start_h=`date -u +%H`
    start_m=`date -u +%M`
    start_s=`date -u +%S`
    start_h=`expr $start_h \* 3600`
    start_m=`expr $start_m \* 60`
    start_date_h=`expr $now - $start_h - $start_m - $start_s`
    start_date_d=`expr $start_date_h + 86400`

    cat $tmp_a | tail -8 | awk -F"|" '{ print $1}'>>$tmp_b
    cat $tmp_a | tail -8 | awk -F"|" '{ print $2}'>>$tmp_b
    cat $tmp_a | tail -8 | awk -F"|" '{ print $3}'>>$tmp_b

    echo '{"data format":"[date_time(UTC), kp_index, moon_size]", "next_hours":['>$tmp_a

    for i in `cat $tmp_b | sed "s/ (G/:G/; s/)//"`
        do
            previous_time_segment=`expr $now - 10800` 
            date_pom=`date -ur $start_date_h "+%Y%m%d%H"`
            if [  $start_date_h -gt $previous_time_segment ]; then
                kp=`echo $i`
                a=`/usr/games/pom $date_pom | sed "s/.*Moon is //g; s/ (.*//g" | tr -d "\n"`
            
                if [ "$a" == "at the First Quarter" ] || [ "$a" == "at the Last Quarter" ]; then s=50
                elif [ "$a" == "Full" ]; then s=100
                elif [ "$a" == "New" ]; then s=0
                else
                    s=`/usr/games/pom $date_pom | sed "s/.*(//g; s/%.*//g" | tr -d "\n"`
                fi

                if [ "$a" == "Waning Gibbous" ] || [ "$a" == "at the Last Quarter" ] || [ "$a" == "Waning Crescent" ]; then 
                    s=`expr $s \* -1`
                fi

                echo '['$start_date_h', "'$kp'", '$s']'>>$tmp_a
            fi
            start_date_h=`expr $start_date_h + 10800`
        done

    cat $tmp_a | tr -d "\n" | sed 's/\]\[/\], \[/g; s/$/],&/'>$tmp_b
    
    url='https://services.swpc.noaa.gov/text/27-day-outlook.txt'
    da=`date -ur $start_date_d "+%Y %b %d"`

    ftp -o - $url | sed -n "/$da/,\$p" | sed '$d' | awk '{ print substr($0,length,1) }' >$tmp_a

    echo ' "next_days":['>>$tmp_b
    
    for i in `cat $tmp_a`
        do
            kp=$i
            date_pom=`date -ur $start_date_d "+%Y%m%d%H"`
            a=`/usr/games/pom $date_pom | sed "s/.*Moon is //g; s/ (.*//g" | tr -d "\n"`

            if [ "$a" == "at the First Quarter" ] || [ "$a" == "at the Last Quarter" ]; then s=50
            elif [ "$a" == "Full" ]; then s=100
            elif [ "$a" == "New" ]; then s=0
            else
                s=`/usr/games/pom $date_pom | sed "s/.*(//g; s/%.*//g" | tr -d "\n"`
            fi

            if [ "$a" == "Waning Gibbous" ] || [ "$a" == "at the Last Quarter" ] || [ "$a" == "Waning Crescent" ]; then
                s=`expr $s \* -1`
            fi

            echo '['$start_date_d', "'$kp'", '$s']'>>$tmp_b
            start_date_d=`expr $start_date_d + 86400`
        done

    cat $tmp_b | tr -d "\n" | sed 's/\]\[/\], \[/g; s/$/]}&/'>/var/www/aurora/pub/aurora_forecast.json
    rm $tmp_b
    chown -R www:www /var/www/aurora/pub/
    chmod -R 755 /var/www/aurora/pub/
else
    echo "Something's TERRIBLY wrong with the 48 aurora report" | mail -s"aurora next hours error" hugo
fi
rm $tmp_a
